[project]
name = "turing-bench"
version = "0.1.0"
description = "Graph database benchmarking tool from TuringDB"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "turingdb>=1.16",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "ruff>=0.14.14",
]
