[project]
name = "turing-bench"
version = "0.1.0"
description = "Graph database benchmarking tool from TuringDB"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "turingdb>=1.16",
]
